# Generated by Django 6.0.5 on 2026-05-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('plant', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
